_select_data:
  aspect-ratios:
    - square
    - portrait
    - portrait-tall
    - landscape
    - landscape-wide

  column-sizes:
    col-6: One Half
    col-12: Full Width
    col-4: One Third
    col-3: One Quarter
    col-6_sm-12: One Half (Stacked)
    col-4_sm-12: One Third (Stacked)
    col-3_sm-12: One Quarter (Stacked)

# achtung Spelling immer mehrzahl verwenden - auch Gallery wird zu Galleries
  gallery-background-standard-galleries:
    bg-light: White Background
    bg-dark: Dark Background
    bg-featured: Featured Background
